### ISSUE TITLE
SerialHelper.getInstance().sendData(p) 佬 这个发送成功后怎么知道发送成功还是失败

### ISSUE THREAD

**Issue by 15620879530** [alanqjt/SerialPortHelper#10]

**Comment by alanqjt** [comment]
串口通讯的本质是写文件， java 层的 write方法是void.如果想要知道自己有没有真正的发送给下位机，那必须要在定制的通讯协议时，以应答模式这种来定制    /**
     * Writes <code>b.length</code> bytes from the specified byte array
     * to this output stream. The general contract for <code>write(b)</code>
     * is that it should have exactly the same effect as the call
     * <code>write(b, 0, b.length)</code>.
     *
     * @param      b   the data.
     * @exception  IOException  if an I/O error occurs.
     * @see        java.io.OutputStream#write(byte[], int, int)
     */
    public void write(byte b[]) throws IOException {
        write(b, 0, b.length);
    }
