### ISSUE TITLE
java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by NickTet** [alanqjt/SerialPortHelper#2]
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.alan.serial-5b1EKT_gfeLFU7JRJ9a-lQ==/lib/arm/libserial_port.so" has text relocations

大佬 这个问题咋个破

**Comment by alanqjt** [comment]
是没有你需要的这个CPU架构的so 包，在网上或者自己去生成一个就好
