### ISSUE TITLE
请问能改成一发两回的形式？

### ISSUE THREAD

**Issue by my29** [alanqjt/SerialPortHelper#4]
发第一条指令
马上回第一条指令
间隔100s
回第二条指令

**Comment by alanqjt** [comment]
可以在OnSerialPortDataListener 里面的onDataReceived方法中处理，当接收到第一条指令后 SerialHelper.getInstance().sendData("回复第一条指令");
//倒计时100S 处理      Thread.sleep()  或者 CountdownTimer   handler都可以
SerialHelper.getInstance().sendData(回复第二条指令);   
其实就是在接收数据的listener里面做事情，至于对每个动作怎么处理就看你怎么写

**Comment by waleswood** [comment]
能支持同时打开两个串口进行通信嘛？我看你用的单例模式
