### ISSUE TITLE
粘包问题处理了吗？

### ISSUE THREAD

**Issue by waleswood** [alanqjt/SerialPortHelper#7]

**Comment by alanqjt** [comment]
如果配置没有问题，即使是同一时间下位机发送了多条报文回来，也会通过listener多次返回每一条报文

**Comment by waleswood** [comment]
嗯嗯，那丢包问题呢？就是有可能收到了一帧报文的前半部分，后半部丢了。

**Comment by alanqjt** [comment]
粘包和分包都是同一个道理，测试能不能处理分包和粘包，直接运行Demo,然后用串口助手把一条信息分开两三条消息发送，或者一次性发送很多条消息
